### ISSUE TITLE
Test Adapter for Google Test cannot execute tests

### ISSUE THREAD

**Issue by spebl** [microsoft/vstest#2848]
## Description
Google Tests cannot be run using the Test Adapter for Google Test that ships with Visual Studio with C++ installed.

## Steps to reproduce
Using a Visual studio 16.10 preview build with "Desktop development with C++ installed".
File->New->Project and create a Google Test project choosing all the default options.
Open the Test Explorer.
Build the sample test.
Notice the test is discovered.
Run the test in the Test Explorer.

## Expected behavior
Test is successfully run.

## Actual behavior
The test is not run, and there is an error in the Tests output window pane "Could not find test executor with URI 'executor://testadapterforgoogletest/v1'.  Make sure that the test executor is installed and supports .net runtime version  ."

## Diagnostic logs
I’ve enabled “Trace” logs from Test->Options->Logging Level. That puts out diagnostic test platform logs under %temp%\TestPlatformLogs. Looking at the vstest.console log (logs.txt) I see that the Test Explorer is initializing the platform with google test adapter:

TpTrace Information: 0 : 16128, 1, 2021/04/08, 06:15:13.075, 10351613562, vstest.console.exe, DesignModeClient.ProcessRequests: Processing Message: (Extensions.Initialize) -> [
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\COMMONEXTENSIONS\\MICROSOFT\\EBF\\TESTEXPLORER\\Microsoft.VisualStudio.Workspace.ExternalBuildFramework.TestProvider.dll",
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\EXTENSIONS\\FHJUPEZ5.Z5O\\BoostTestAdapter.dll",
  **"C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\EXTENSIONS\\FYY32XX5.ELU\\GoogleTestAdapter.TestAdapter.dll",**
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\EXTENSIONS\\MICROSOFT\\NODEJSTOOLS\\TESTADAPTER\\Microsoft.NodejsTools.TestAdapter.dll",
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\EXTENSIONS\\MICROSOFT\\PYTHON\\CORE\\Microsoft.PythonTools.TestAdapter.Executor.dll"
]

The discovery process logs also indicate that the adapter is passed on to it (logs.host*_6.txt):

TpTrace Information: 0 : 13920, 7, 2021/04/08, 06:15:13.712, 10357985541, testhost.x86.exe, TestRequestHandler.ProcessRequests: received message: (TestDiscovery.Initialize) -> [
  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\intprev\\Common7\\IDE\\Extensions\\TestPlatform\\Extensions\\Microsoft.Cci.dll",
….
  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\intprev\\Common7\\IDE\\Extensions\\TestPlatform\\Extensions\\Microsoft.VisualStudio.TraceDataCollector.dll",
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\COMMONEXTENSIONS\\MICROSOFT\\EBF\\TESTEXPLORER\\Microsoft.VisualStudio.Workspace.ExternalBuildFramework.TestProvider.dll",
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\EXTENSIONS\\FHJUPEZ5.Z5O\\BoostTestAdapter.dll",
  **"C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\EXTENSIONS\\FYY32XX5.ELU\\GoogleTestAdapter.TestAdapter.dll",**
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\EXTENSIONS\\MICROSOFT\\NODEJSTOOLS\\TESTADAPTER\\Microsoft.NodejsTools.TestAdapter.dll",
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\EXTENSIONS\\MICROSOFT\\PYTHON\\CORE\\Microsoft.PythonTools.TestAdapter.Executor.dll"
]

The test execution process logs on the other hand do not get initialized with the adapter(logs.host*_10.txt):

TpTrace Information: 0 : 3600, 8, 2021/04/08, 06:15:16.140, 10382260681, testhost.x86.exe, TestRequestHandler.ProcessRequests: received message: (TestExecution.Initialize) -> [
  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\intprev\\Common7\\IDE\\Extensions\\TestPlatform\\Extensions\\Microsoft.Cci.dll",
…
  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\intprev\\Common7\\IDE\\Extensions\\TestPlatform\\Extensions\\Microsoft.VisualStudio.TraceDataCollector.dll",
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\COMMONEXTENSIONS\\MICROSOFT\\EBF\\TESTEXPLORER\\Microsoft.VisualStudio.Workspace.ExternalBuildFramework.TestProvider.dll",
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\INTPREV\\COMMON7\\IDE\\EXTENSIONS\\MICROSOFT\\NODEJSTOOLS\\TESTADAPTER\\Microsoft.NodejsTools.TestAdapter.dll"
]

## Environment
Visual studio 16.10 Preview 3.0

[AB#1315248](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1315248)

**Comment by Sanan07** [comment]
I was able to repro the issue, strange thing is that it works well in VS 16.10.0 Preview 1.0. 
Maybe @Haplois changes related to fqn might cause it, cause I do not recall any change which we did recently could result this issue.

**Comment by Haplois** [comment]
@Sanan07, we fixed a couple of issues with FQN on our v16.10 preview bits. Could you test with that again?

**Comment by Sanan07** [comment]
@Haplois I tested in 16.10.0 Preview 3.0 [31223.327.main] still does not work, while in 16.10.0 Preview 2.1 works well.

**Comment by Haplois** [comment]
@Sanan07, can you check the exact TP version on that version?

**Comment by Sanan07** [comment]
VS version which does not work shows TP version 16.10.0, VS which works has 16.10.0-dev.

**Comment by jakubch1** [comment]
I was able to reproduce it and it looks like TestWindow issue:

Before discovery TP receives:
TpTrace Information: 0 : 37296, 1, 2021/04/27, 08:44:41.064, 6933550624253, vstest.console.exe, DesignModeClient.ProcessRequests: Processing Message: (Extensions.Initialize) -> [
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\PREVIEW\\COMMON7\\IDE\\COMMONEXTENSIONS\\MICROSOFT\\EBF\\TESTEXPLORER\\Microsoft.VisualStudio.Workspace.ExternalBuildFramework.TestProvider.dll",
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\PREVIEW\\COMMON7\\IDE\\EXTENSIONS\\FHJUPEZ5.Z5O\\BoostTestAdapter.dll",
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\PREVIEW\\COMMON7\\IDE\\EXTENSIONS\\RRFTGT4X.BTP\\GoogleTestAdapter.TestAdapter.dll"
]

but before test execution TW sends additional request:

TpTrace Information: 0 : 37296, 1, 2021/04/27, 08:44:57.398, 6933713967761, vstest.console.exe, DesignModeClient.ProcessRequests: Processing Message: (Extensions.Initialize) -> [
  "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO\\2019\\PREVIEW\\COMMON7\\IDE\\COMMONEXTENSIONS\\MICROSOFT\\EBF\\TESTEXPLORER\\Microsoft.VisualStudio.Workspace.ExternalBuildFramework.TestProvider.dll"
]

Second request doesn't contain Google Test Adapter and this is the reason why we  do not execute tests.

In 16.9 there TW is not sending any additional Extensions.Initialize before test execution.

What is interesting if you keep changing x86 -> x64 -> x86 before each test execution then it works correctly in 16.10, but if you run it second time keeping same architecture it fails.

**Comment by spebl** [comment]
This also seems to be happening with the Test Adapter for Boost.Test, so it looks to be bigger than just a Google Test issue.

**Comment by Sanan07** [comment]
After TW fix, tested for Google Test Adapter in  VS  16.10 Preview 3.0 [31230.346.main] and works fine. @spebl please check it.

**Comment by spebl** [comment]
Yep! Looks to be working now in the latest build. Thank you!

**Comment by sudheeshps** [comment]
I have found this issue in VS 2022 Community Edition.

VS 2022 build info:
```
Microsoft Visual Studio Community 2022
Version 17.13.6
```
Here the issue is that even if Google Test Adapter is installed by VS installer, the binaries are not getting copied to `TestPlatform\Extensions` folder.

The best way to check is that open the VS 2002 Developer Command Prompt and run the following command:
vstest.console.exe /ListExecutors. It shall list Google Test Adapter. But in case of this issue, it will not. 

**Before fix:**

C:\Program Files\Microsoft Visual Studio\2022\Community>vstest.console /ListExecutors
VSTest version 17.13.0 (x64)

The following Test Execution Add-Ins are available:
```
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://CodedWebTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://MSTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://WebTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://CppUnitTestExecutor/v1
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://UAPCppExecutorIdentifier
```

**After fix:**

C:\Program Files\Microsoft Visual Studio\2022\Community>vstest.console /ListExecutors
VSTest version 17.13.0 (x64)

The following Test Execution Add-Ins are available:
```
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://TestAdapterForGoogleTest/v1
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://CodedWebTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://MSTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://WebTestAdapter/v1
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://CppUnitTestExecutor/v1
Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator
        Uri: executor://UAPCppExecutorIdentifier
```

**Work around:**

The workaround I have tried is that copy Google Test Adapter binaries from the following folder:
"`C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\uyaomxya.2er`" (note sure folder name `uyaomxya.2er` is same for Google Test Adapter extension in all machines) to
"`C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\TestPlatform\Extensions`" folder.

I tried adding the first folder to `PATH `variable, but didn't help.

The following are the binaries to be copied:
```
GoogleTestAdapter.Common.dll
GoogleTestAdapter.Common.Dynamic.dll
GoogleTestAdapter.Core.dll
GoogleTestAdapter.DiaResolver.dll
GoogleTestAdapter.TestAdapter.dll
```
Once "`C:\Program Files\Microsoft Visual Studio\2022\Community>vstest.console /ListExecutors`" works as expected, test explorer also runs the tests.

**Comment by nohwnd** [comment]
https://github.com/microsoft/TestAdapterForGoogleTest Please report it here .

**Comment by sudheeshps** [comment]
> https://github.com/microsoft/TestAdapterForGoogleTest Please report it here .

Thank you @nohwnd for the headsup! I have created an issue there.

**Comment by ashesman** [comment]
Thankyou @sudheeshps for the workaround.  Really helped me out.  My folder was named 114tfvkx.br0, so the folder is install/version specific named.

**Comment by sudheeshps** [comment]
Happy to know that it helped @ashesman ! Thank you 👍
