### ISSUE TITLE
The reason why the test run was aborted is not indicated.

### ISSUE THREAD

**Issue by zwcloud** [Microsoft/vstest#527]
## Description
When `StackoverflowException` happens, no reason is indicated in the output.

## Steps to reproduce

```CSharp
using Xunit;

namespace XUnitTestProject1
{
    public class UnitTest1
    {
        public class Class1
        {
            public static bool Fun()
            {
                Fun();
                return true;
            }
        }

        [Fact]
        public void Test1()
        {
            Assert.True(Class1.Fun());
        }
    }
}
```

## Expected behavior
The output contains the reason why the test run was aborted. For example:
_Process is terminated due to StackOverflowException._

## Actual behavior
> ------ Discover test started ------
> [xUnit.net 00:00:01.1107388]   Discovering: XUnitTestProject1
> [xUnit.net 00:00:01.3233828]   Discovered:  XUnitTestProject1
> ========== Discover test finished: 1 found (0:00:02.253) ==========
> ------ Run test started ------
> [xUnit.net 00:00:00.9959544]   Starting:    XUnitTestProject1
> The active Test Run was aborted.
> ========== Run test finished: 0 run (0:00:04.260) ==========

## Environment
Win10, VS2017RC

```XML
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170210-02" />
<PackageReference Include="xunit" Version="2.2.0-rc2-build3523" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-rc2-build1249" />
```
-----
It's better to let the user know why the test run was aborted. In my case, may be showing something like _Process is terminated due to StackOverflowException._ That's what dotnet core console app have done:
After `Class1.Fun()` was called in a console app, the console showed that message:
![devenv_2017-02-14_23-09-26](https://cloud.githubusercontent.com/assets/6965758/22934809/48c952aa-f30b-11e6-99df-16ddf851b80a.png)

Related issue: https://github.com/xunit/xunit/issues/1111

**Comment by ajcvickers** [comment]
@smadala Any update on this issue? It was created in February but does not seem to have been triaged. We are seeing this issue when running Entity Framework tests and after much discussion we can think of no way forward other than getting more info about the failure from the test runner. It would also be great to know if there is any other way for us to get more info in this situation.

/cc @Eilon @smitpatel

**Comment by smadala** [comment]
Dup of https://github.com/Microsoft/vstest/issues/627, fix is available in VS15.3.0 preview2.

**Comment by AmadeusW** [comment]
The test runner still does not provide the reason for StackOverflowException (neither test name nor stack trace).
The issue still happens in 15.7 (`Microsoft (R) Test Execution Command Line Tool Version 15.7.1`) and 15.8 preview 2 internal dogfood (`Microsoft (R) Test Execution Command Line Tool Version 15.0.27713.0`) and whatever runs on the CI server (`Microsoft (R) Test Execution Command Line Tool Version 15.6.0`)

**Comment by smadala** [comment]
@AmadeusW I have update my comment(https://github.com/Microsoft/vstest/issues/527#issuecomment-310281977).
