### ISSUE TITLE
Unable to see Code Coverage Results from VS 2017

### ISSUE THREAD

**Issue by codito** [Microsoft/vstest#909]
Copied from https://github.com/Microsoft/vstest-docs/issues/56 on behalf of @SrivatsaMarichi

Hi Team,

I have added the package for Code Coverage from the Package Manager Console by passing Install-Package Microsoft.CodeCoverage -Version 1.0.3.

I then ran Analyze Code Coverage but I don't see any results in Code Coverage Results window.

I am trying this for .NetCoreApp 1.0, Can anyone help me out here?

Visual Studio Enterprise 2017 Version- 15.2(26430.6)

Also I want to know is there a support for the same on VSTS CI builds? If so, how?

Thanks,
Srivatsa

**Comment by SrivatsaMarichi** [comment]
Any help here?

**Comment by Faizan2304** [comment]
@mayankbansal018 Can you please take a look.

**Comment by codito** [comment]
@SrivatsaMarichi can you please share csproj of test project?

**Comment by codito** [comment]
Steps to enable code coverage is detailed in https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#setup-a-project.

In CI, it is possible to use this command line: https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#collect-coverage-with-command-line-runner

**Comment by codito** [comment]
Connected with @SrivatsaMarichi offline. This issue is resolved now.

**Comment by Allann** [comment]
I still can't see results.  The menu item is there but disabled (vs2017 build 26430.15).  I have included the all the things in the "Steps to enable code coverage" link mentioned above.  I have even restarted vs2017, dotnet restore, etc with no luck.

What was the fix?

**Comment by codito** [comment]
@Allann `26430.15` build is VS 2017 15.2. The coverage feature requires VS 2017 15.3+ build: https://www.visualstudio.com/vs/preview/.

**Comment by adam-geisen** [comment]
I'm still getting this issue using a mixed solution of .net framework 4.6.2, .net Standard 2.0, and .net core 2.1... 

Are you sure this isn't still happening? My projects using .net standard aren't showing up at all.
